metricbeat.modules:
  - module: docker
    metricsets:
      [
        "container",
        "cpu",
        "diskio",
        "event",
        "healthcheck",
        "image",
        "info",
        "memory",
        "network",
      ]
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s

  - module: elasticsearch
    metricsets: ["node", "node_stats", "cluster_stats", "index"]
    hosts: ["https://es01:9200"]
    period: 10s
    ssl.verification_mode: none
    username: "elastic"
    password: "senhaforte12345678"

output.elasticsearch:
  hosts: ["https://es01:9200"]
  ssl.certificate_authorities: ["config/certs/ca/ca.crt"]
  username: "elastic"
  password: "senhaforte12345678"

setup.kibana:
  host: "kibana:5601"
  username: "elastic"
  password: "senhaforte12345678"

setup.dashboards.enabled: true
